# Generated by Django 4.2.13 on 2024-08-09 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 20, 56, 34, 611484, tzinfo=datetime.timezone.utc)),
        ),
    ]
