# Generated by Django 4.2.13 on 2024-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
